kind: pipeline
type: docker
name: default

steps:
  - name: Use Plugin to push event to dt environment
    image: cavejay/dynatrace-drone-events
    settings:
      dynatrace_environment:
        from_secret: dtenv
      dynatrace_api_token:
        from_secret: dttoken
      tagrules:
        - HOST=tada-discord
