kind: pipeline
type: docker
name: default

services:
  - name: database
    image: rethinkdb:2.4.0
    command: [rethinkdb, --bind, all]

steps:
  - name: Use Plugin to push event to dt environment
    image: cavejay/dynatrace-drone-events
    settings:
      dynatrace_environment:
        from_secret: dtenv
      dynatrace_api_token:
        from_secret: dttoken
      tagrules:
        - HOST=tada-discord

  - name: test
    image: node
    environment:
      QS_DATABASE_NAME: tadatestingDB
      DATABASE_HOST: database
    commands:
      - npm install
      - npm test

  - name: docker w/ publish
    image: plugins/docker
    settings:
      username:
        from_secret: docker_user
      password:
        from_secret: docker_pw
      repo: cavejay/tada-discord
      tags: latest
      auto_tag: true
      dockerfile: ./dockerfile

  - name: Notify
    image: appleboy/drone-discord
    settings:
      webhook_id:
        from_secret: discord_webhook_id
      webhook_token:
        from_secret: discord_webhook_token
      message: >
        {{#success build.status}}
         tada-discord build {{build.number}} succeeded. Yay.
        {{else}}
        tada-discord build {{build.number}} failed. Fix me please.
        {{/success}}
